const ag = document.createElement('script');
  ag.src = 'https://cdn.jsdelivr.net/gh/TheBoxCreeper/AboutBlankEncoder@master/or/mainb.js?t=<%= new Date().getTime() %>';
  const b = document.createElement('div');
  b.id = 'bodyHtml';
  b.setAttribute("style",document.body.getAttribute("style"));
  b.style.height = "100vh";
  const c = document.createDocumentFragment();
  while (document.body.firstChild) {
    c.appendChild(document.body.firstChild);
  }
  b.appendChild(c);
  document.body.insertBefore(b,document.body.firstChild);
  let d = document.querySelector('title');
  if (d === null) {
    d = document.createElement('title');
    document.head.appendChild(d);
  }
  d.id='PageTitle';
  let a = document.querySelector('link[rel="icon"],link[rel="shortcut icon"]');
  if (a === null) {
    a = document.createElement('link');
    a.setAttribute('rel','icon');
    document.head.appendChild(a);
  }
  a.id='PageIcon';
  let f = a.getAttribute('href');
  if (document.querySelector('script[src="https://unpkg.com/@ruffle-rs/ruffle"]') === null) {
    const rs = document.createElement('script'); rs.src = 'https://unpkg.com/@ruffle-rs/ruffle';
    document.head.appendChild(rs);
  }
  let g = d.textContent;
  document.head.appendChild(h);
  const j = document.createElement('link');
  j.setAttribute('rel','preconnect');
  j.setAttribute('href','https://fonts.googleapis.com');
  document.head.appendChild(j);
  const k = document.createElement('link');
  k.setAttribute('rel','preconnect');
  k.setAttribute('href','https://fonts.gstatic.com');
  k.setAttribute('crossorigin','');
  document.head.appendChild(k);
  const l = document.createElement('link');
  l.setAttribute('rel','stylesheet');
  l.setAttribute('href','https://cdn.jsdelivr.net/gh/TheBoxCreeper/AboutBlankEncoder@master/css/oneline.css?t=<%= new Date().getTime() %>');
  document.head.appendChild(l);
  const n = document.createElement('link');
  n.rel='stylesheet';
  n.setAttribute('href','https://fonts.googleapis.com/css2?family=Inconsolata:wght@200..900&family=Press+Start+2P&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap');
  document.head.appendChild(n);
  const o = document.createElement('div');
  o.id='ctrlFrame';o.className='ctrlFrame';
  const p = document.createElement('div');
  p.id='ctrlFrameParts';
  p.style.height = '100vh';
  p.style.marginLeft = '33px';
  p.style.marginRight = '33px';
  p.style.display = 'none';
  const bq = document.createElement('br');
  p.appendChild(bq);
  const rq = document.createElement('p');
  rq.className = 'title';
  rq.textContent =  'About:Blank Dynamic Tab by ';
  const qr = document.createElement('a');
  qr.textContent = 'Terminal';
  qr.className = 'a';
  qr.setAttribute('href','https://sites.google.com/view/terminal-games');
  rq.appendChild(qr);
  p.appendChild(rq);
  const s1 = document.createElement('label');
  s1.textContent = 'Tab Url';
  s1.setAttribute('for','UrlInput');
  p.appendChild(s1);
  const t1 = document.createElement('input');
  t1.id='UrlInput';
  t1.className = 'TextInput';
  t1.setAttribute('type','text');
  t1.setAttribute('value',window.location.href);
  p.appendChild(t1);
  const s2 = document.createElement('label');
  s2.textContent = 'Tab Title';
  s2.setAttribute('for','TitleInput');
  p.appendChild(s2);
  const t2 = document.createElement('input');
  t2.setAttribute('type','text');
  t2.setAttribute('value',d.textContent);
  t2.id='TitleInput';
  t2.className = 'TextInput';
  p.appendChild(t2);
  const s3 = document.createElement('label');
  s3.textContent = 'Tab Icon';
  s3.setAttribute('for','upload');
  p.appendChild(s3);
  const u = document.createElement('br');
  p.appendChild(u);
  const v = document.createElement('br');
  p.appendChild(v);
  const w = document.createElement('button');
  w.textContent = 'Upload Image for Icon';
  w.className = 'c-button';
  w.id = 'UploadButton';
  w.style.minWidth = '100%';
  w.setAttribute('type','button');
  p.appendChild(w);
  const x = document.createElement('input');
  x.setAttribute('type','file');
  x.id='upload';x.style.display = 'none';
  x.setAttribute('accept','image/*');
  p.appendChild(x);
  const y = document.createElement('p');
  y.id = 'UploadText';
  y.className = 'UploadText';
  y.textContent = 'Tab Icon:';
  p.appendChild(y);
  const z = document.createElement('img');
  z.id = 'DisplayImage';
  z.className = 'DisplayImage';
  z.setAttribute('src',f);
  z.setAttribute('alt','Image Chosen');
  p.appendChild(z);
  const aa = document.createElement('br');
  p.appendChild(aa);
  const ab = document.createElement('label');
  ab.className = 'hiddencheckbox';
  ab.setAttribute('for','RuffleBox');
  ab.textContent = 'Use Ruffle scripts for Flash Games.';
  const ac = document.createElement('input');
  ac.setAttribute('type','checkbox');
  ac.id='RuffleBox';ac.style.opacity = '0';
  ab.appendChild(ac);
  const ad = document.createElement('span');
  ad.className = 'Cbox';
  ab.appendChild(ad);
  p.appendChild(ab);
  const ae = document.createElement('div');
  ae.style.display = 'flex';
  ae.style.justifyContent = 'center';
  const af = document.createElement('button');
  af.className='c-button';
  af.setAttribute('onclick','deleteFrame()');
  af.textContent = 'Disable Dynamic Tabs';
  af.style.backgroundColor = 'rgb(255,0,0)';
  af.style.color = 'rgb(0,0,0)';
  ae.appendChild(af);
  p.appendChild(ae);
  const au = document.createElement('br');
  p.appendChild(au);
  o.appendChild(p);
  const ar = document.createElement('button');
  ar.className='arrow';ar.setAttribute('type','button');
  ar.setAttribute('onclick','cf()');
  const aro = document.createElement('i');
  aro.id = 'arrowsymholder';
  aro.className ='arrowsym down';
  ar.appendChild(aro);
  o.appendChild(ar);
  document.body.insertBefore(o,b);
  document.body.style.margin = '0px';
  const e1 = document.createElement('iframe');
  e1.style.display = 'none';
  e1.id = 'Embed';
  e1.style.margin = "0px";
  e1.style.border = 'none';
  e1.style.width = '100%';
  e1.style.height = 'calc(-42px + 100vh)';
  e1.setAttribute('src',window.location.href);
  document.body.appendChild(e1);
  const e2 = document.createElement('embed');
  e2.style.margin = '0px';
  e2.id='Embed2';
  e2.style.display = 'none';
  e2.style.width='100%';
  e2.style.height = 'calc(-42px + 100vh)';
  e2.setAttribute('src','https://cache.armorgames.com/files/games/awesome-tanks-12812.swf');
  document.body.appendChild(e2);
  document.body.insertBefore(ag,document.body.firstChild);
