const site = "https://sites.google.com/view/terminal-games";
const drive = "https://drive.google.com/drive/folders/1Fc5m2RE5XyS05-HWORFb7ptZXnn5fAxd";
const file = "https://drive.usercontent.google.com/u/0/uc?id=14KXNPDGLcU9Z4B2aGslmBmtdbw9JlD2j&export=download";
const upbutton = 1;
const button = document.getElementById("update");
const vdiv = document.getElementById("version");
const version = vdiv.className;
const latest = 8;
document.getElementById("TitleLink").setAttribute("href",site);
document.getElementById("drive").setAttribute("href",drive);
console.log(version);
